Hw2
s0mth1ng/2019-2-Track-Frontend-M-Ivanov pull request #2
Opened 2019-10-12 00:15 UTC by s0mth1ng

# Домашнее задание № 2
Прошу @martinkomitsky, @chexex, @priver проверить его.
Что было сделано:
* написан чат, с localStorage.
* добавлен линтер.

2019-10-12 12:05 UTC, priver reviewed
нужно задеплоить на github pages и указать в этом PR ссылку

2019-10-12 12:05 UTC, priver commented on web-components/false/_cacache/index-v5/34/8e/30c54cce758990bcd1b33114c4aa8a9e5a25c152ac39d9feab22b7e13e00
> +2f23908fc24ac3b1c93fe20141e0fa74a7939307	{"key":"make-fetch-happen:request-cache:https://registry.npmjs.org/-/npm/v1/security/audits/quick","integrity":null,"time":1569870720627}
это что вообще за файл?

2019-10-12 12:05 UTC, priver commented on web-components/src/components/ChatContainer.js
> +    for (let i = 0; i < localStorage.length; ++i) {
Нужно создать массив `messages` и записать его в `localStorage` целиком в один ключ. Иначе мы весь сторадж под один чат заняли.

Как поведет себя программа, если я запишу в  `localStorage` ключ `myKey`? `length` увеличится на 1, а элемента с ключем `[length - 1]` в сторадже не будет

2019-10-12 12:05 UTC, priver commented on web-components/src/components/ChatContainer.js
> +      if (localStorage.getItem(localStorage.key(i)) !== 'INFO') {
приходится вот такие костыли с `INFO` делать

2019-10-12 12:05 UTC, priver commented on web-components/src/components/ChatContainer.js
> +    this.cnt = 0;
для чего это счетчик?

2019-10-12 13:29 UTC, s0mth1ng commented on web-components/false/_cacache/index-v5/34/8e/30c54cce758990bcd1b33114c4aa8a9e5a25c152ac39d9feab22b7e13e00
> +2f23908fc24ac3b1c93fe20141e0fa74a7939307	{"key":"make-fetch-happen:request-cache:https://registry.npmjs.org/-/npm/v1/security/audits/quick","integrity":null,"time":1569870720627}
Не знаю. Я ничего там не редактировал вручную, мне его удалить?

2019-10-12 13:30 UTC, s0mth1ng commented on web-components/src/components/ChatContainer.js
> +    this.cnt = 0;
Тестировал полученные сообщения, забыл убрать.

2019-10-12 13:48 UTC, priver commented on web-components/false/_cacache/index-v5/34/8e/30c54cce758990bcd1b33114c4aa8a9e5a25c152ac39d9feab22b7e13e00
> +2f23908fc24ac3b1c93fe20141e0fa74a7939307	{"key":"make-fetch-happen:request-cache:https://registry.npmjs.org/-/npm/v1/security/audits/quick","integrity":null,"time":1569870720627}
Добавь эту папку в gitignore и удали c помощью `git rm --cached`

2019-10-12 13:49 UTC, priver commented on web-components/src/components/ChatContainer.js
> +    this.cnt = 0;
ты можешь не отвечать, а просто его удалить тогда, гитхаб сам поймет

2019-10-12 15:36 UTC, s0mth1ng commented
Можете, пожалуйста, подробнее объяснить что нужно сделать с gh-pages?

2019-10-14 07:30 UTC, chexex commented
Со сборкой все ок, но внешне не хватает элементов 
https://s0mth1ng.github.io/2019-2-Track-Frontend-M-Ivanov/

2019-10-14 10:34 UTC, priver requested changes
Нужно добавить шапку

2019-10-15 14:13 UTC, priver approved these changes
Отлично, 12 баллов

2019-10-15 14:14 UTC, merged