Hw7
s0mth1ng/2019-2-Track-Frontend-M-Ivanov pull request #6
Opened 2019-11-23 16:58 UTC by s0mth1ng

# Домашнее задание №7

Прошу @martinkomitsky, @chexex, @priver проверить его.
Что было сделано:
* Добавлена отправка картинок. Можно прикрепить с помощью кнопки аттача. Либо drag&drop'ом в поле ввода. 
* Добавлена геолокация. Отправляется кликабельная ссылка.
* Добавлены аудиосообщения. Начать запись и остановить можно по одной кнопке(при записи кнопка красная).

https://s0mth1ng.github.io/2019-2-Track-Frontend-M-Ivanov/

2019-12-03 13:22 UTC, priver requested changes

2019-12-03 13:22 UTC, priver commented on src/components/Input.js
> +	const [recordButton, setRecordButton] = useState(startRecording);
не нужно хранить иконки в стейте.

2019-12-03 13:22 UTC, priver commented on src/components/Input.js
> +		if (recordButton === startRecording) {
вот это совсем прям плохо, "если иконка сейчас такая, то делаем такое то действие" - это неправильная логика.
правильно: "сейчас происходит запись (состояние нашего компонента), поэтому у кнопки такая иконка и по ее нажатию происходит такое то действие"

2019-12-03 13:22 UTC, priver commented on src/components/Input.js
> +		const record = document.getElementById('record');
это не react-way
не нужно искать кнопки через `getElementById `, нужно добавить этой кнопке (в том месте где она рендерится) свойство `onClick` и прочее

2019-12-03 13:22 UTC, priver commented on src/components/Input.js
> +		const fileInput = document.getElementById('fileInput');
аналогично, не нужно `getElementById `

2019-12-03 18:51 UTC, s0mth1ng commented on src/components/Input.js
> +		const record = document.getElementById('record');
Добрый вечер! Можете подсказать как это исправить? Если получать кнопку из event.target вообще не работает корректно( 
Повесить два хэндлера на две картинки не получается, потому что не понятно откуда брать mediaRecorder.

2019-12-05 13:44 UTC, priver commented on src/components/Input.js
> +		const record = document.getElementById('record');
https://github.com/s0mth1ng/2019-2-Track-Frontend-M-Ivanov/pull/6/files#diff-176a75723b270d2f21cd7ca836987318R117

у тебя на этой строке уже добавлен обработчик события. надо его не удалять/добавлять, а уже в самом обработчике выполнять разный код в зависимости от условия

2019-12-05 15:04 UTC, s0mth1ng commented on src/components/Input.js
> +		const record = document.getElementById('record');
Я понял, что нужно сделать, но единственное что я придумал, это сделать mediaRecorder глобальным. Можете, пожалуйста, проверить еще раз?

2019-12-05 15:15 UTC, priver requested changes

2019-12-05 15:15 UTC, priver commented on src/components/Input.js
> +		const fileInput = document.getElementById('fileInput');
осталось теперь только от этого избавиться

2019-12-05 15:25 UTC, s0mth1ng commented on src/components/Input.js
> +		const fileInput = document.getElementById('fileInput');
Вроде справился.

2019-12-05 15:47 UTC, priver approved these changes

2019-12-05 15:47 UTC, merged