Exam
s0mth1ng/2019-2-Track-Frontend-M-Ivanov pull request #7
Opened 2019-12-23 19:00 UTC by s0mth1ng

# Домашнее задание №

Прошу @martinkomitsky, @chexex, @priver проверить его.
Что было сделано:

2019-12-27 08:26 UTC, martinkomitsky requested changes
см. сообщение в чате

2019-12-27 10:02 UTC, s0mth1ng commented
Разобрался. Стоял router вместо hashrouter(

2019-12-29 15:21 UTC, martinkomitsky commented on package.json
> +    "typescript": "^3.7.4"
а это зачем?

2019-12-29 15:23 UTC, martinkomitsky commented on exam/src/components/SingleCity.js
> +	let [country, setCountry] = useState(props.country);
должно быть const

2019-12-29 15:27 UTC, martinkomitsky commented on exam/src/components/City.js
> +		}
весь этот код можно вынести выше

2019-12-29 15:35 UTC, martinkomitsky approved these changes

2019-12-29 15:35 UTC, martinkomitsky commented on exam/src/components/City.js
> +
мусор

2019-12-29 15:35 UTC, merged